#!/bin/bash

                  sudo yum update -y
                  sudo yum install -y httpd php php-mysqlnd php-fpm php-json telnet net-tools
                  sudo systemctl start httpd
                  sudo systemctl enable httpd

                  # Install MySQL and set up database
                  #touch /etc/yum.repos.d/MariaDB.repo
                  #echo "[mariadb]" >> /etc/yum.repos.d/MariaDB.repo
                  #echo "name=MariaDB" >>  /etc/yum.repos.d/MariaDB.repo
                  #echo "baseurl=https://mirror.mariadb.org/yum/11.6/rhel/9Server/x86_64/" >> /etc/yum.repos.d/MariaDB.repo
                  #echo "gpgkey=https://rpm.mariadb.org/RPM-GPG-KEY-MariaDB" >>  /etc/yum.repos.d/MariaDB.repo
                  #echo "gpgcheck=1" >>  /etc/yum.repos.d/MariaDB.repo
                  #yum install -y mariadb-server 
                #   systemctl start mariadb
                #   systemctl enable mariadb
                  
                #   # Set up WordPress database
                #   mysql -e "CREATE DATABASE wordpress;"
                #   mysql -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY 'Salam';"
                #   mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'localhost';"
                #   mysql -e "FLUSH PRIVILEGES;"

                  # Download and install WordPress
                  sudo wget http://wordpress.org/latest.tar.gz
                  sudo tar -xzf latest.tar.gz
                  sudo cp -r wordpress/* /var/www/html/

                  # Set permissions
                  sudo chown -R apache:apache /var/www/html
                  sudo chmod -R 755 /var/www/html

                  # Create wp-config.php
                  sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
                  sudo sed -i "s/database_name_here/${rds_db_db_name}/" /var/www/html/wp-config.php
                  sudo sed -i "s/username_here/${rds_db_username}/" /var/www/html/wp-config.php
                  sudo sed -i "s/password_here/${rds_db_password}/" /var/www/html/wp-config.php
                  sudo sed -i "s/localhost/${rds_db_endpoint}/" /var/www/html/wp-config.php

                  sudo systemctl restart httpd